default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sattar
  password: sattar
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_recipe_app_development

test:
  <<: *default
  database: food_recipe_app_test

production:
  <<: *default
  database: food_recipe_app_production
  username: food_recipe_app
  password: <%= ENV["FOOD_RECIPE_APP_DATABASE_PASSWORD"] %>
